---
title: "Gregg Woodard"
date: 2018-10-09
---
title: Gregg's Website
author: GitHub User
email: your-email@domain.com
description: > Closes #2

# social links
twitter_username: gwood
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
